### ISSUE TITLE
Sort by severity Problem

### ISSUE THREAD

**Issue by kayhankayihan** [PaytmLabs/nerve#1]
Hi,
Thank you for great tool, its awesome.
I noticed that it did not rank the vulnerabilities in the correct order by severity.
 ( like Critical -> High -> Medium --> Low)

![image](https://user-images.githubusercontent.com/13474628/94755082-f169f780-039b-11eb-8bc5-9ab70feaeb87.png)

**Comment by dolevf** [comment]
This will be solved in the next update 2.5.1.

The page will default to sort by severity., however, the default behaviour will still remain alphabetical sorting.

Thanks for submitting the first bug!

**Comment by kayhankayihan** [comment]
Thank you for fast response, how can i fix it in my docker container?

**Comment by dolevf** [comment]
hi there,

You can simply rebuild the container.
