### ISSUE TITLE
error when trying to build from docker 

### ISSUE THREAD

**Issue by royharoush** [PaytmLabs/nerve#3]
Cannot find a valid baseurl for repo: base/7/x86_64
![image](https://user-images.githubusercontent.com/8113056/94997501-28b2f100-05b4-11eb-8652-47c5216fddff.png)

looking at the commands, it supposed to run on centos ?

**Comment by dolevf** [comment]
hi Roy,

If you build the docker it will use CentOS Yes, but it seems like there's some DNS resolution issue, can you check if you can resolve mirrrorlist.centos.org at all?

**Comment by royharoush** [comment]
just tried on a different server and it's working. closing, thanks !

**Comment by dolevf** [comment]
Thanks for the update. :+1:
