### ISSUE TITLE
feature suggestion: allow specifiying ports using the api

### ISSUE THREAD

**Issue by royharoush** [PaytmLabs/nerve#4]
hi,
it will be very useful if we can specify custom ports using the API 
currently it only allows max ports, which i guess is a translation to nmap's --top-ports ? 
![image](https://user-images.githubusercontent.com/8113056/94997988-8268ea80-05b7-11eb-9ab2-e1bcda86765c.png)

**Comment by dolevf** [comment]
hi Roy, 

Yes, max ports is translated to nmap's top ports.

Custom ports will be introduced in the next release **2.5.3** for both the web interface and the API. Thanks for the suggestion.
